AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TargetRCU:
    Type: Number
  TargetWCU:
    Type: Number

Resources: 
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "Album"
          AttributeType: "S"
        - AttributeName: "Artist"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "Album"
          KeyType: "HASH"
        - AttributeName: "Artist"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: !Ref TargetRCU
        WriteCapacityUnits: !Ref TargetWCU